name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-arch: [amd64]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: install rtmidi
        run: |
          sudo apt-get install librtmidi-dev
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
      - name: Build
        env:
          GOOS: linux
          GOARCH: ${{ matrix.go-arch }}
        run: |
          BINARY=launchpad-super-trigger-${{ matrix.go-os }}-${{ matrix.go-arch }}
          go build -a -o $BINARY -v ./cmd/lst/